name: Update RSS Feeds

on:
  schedule:
    - cron: '0 6 * * *' # Täglich um 06:00 Uhr ausführen
  workflow_dispatch: # Erlaubt manuelles Starten per Klick

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python generate_feeds.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_feeds
